#!/usr/bin/perl
# Copyright (c) 2011 Benjamin Nadland <benjamin.nadland@freenet.de>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use 5.010;
use strict;
use warnings;

use Config::Tiny;
use Mojo::JSON;
use Mojo::UserAgent;
use File::Basename;

my $config     = Config::Tiny->new;
my $configfile = $ENV{"HOME"} . "/.gitconfig";
$config = Config::Tiny->read($configfile);
my $USERNAME = $config->{"github"}->{"user"};
my $PASSWORD = $config->{"github"}->{"password"};

my $reponame;
my $ua;
my $json;
my $message;
my $result;

$reponame = basename(qx/pwd/);
chomp($reponame);

$ua = Mojo::UserAgent->new;

$json = Mojo::JSON->new;
$message = $json->encode({name => $reponame});

$result =
  $ua->post('https://'
    . $USERNAME . ":"
    . $PASSWORD
    . '@api.github.com/user/repos' => $message)->res->json;

my $command =
    "git remote add origin git\@github.com:"
  . $USERNAME . "/"
  . $reponame . ".git";
say `$command`;
say `git push -u origin master`;

